title: Crossing Red-Helios Wiki
description: The official repository of information about the world of Crossing Red-Helios.
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
